# Generated by Django 3.0.7 on 2020-07-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200630_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cusomter',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
